export const PLAYS = [
    {
        id: 0,
        name: "All's Well That Ends Well",
        genre: "Comedy",
        difficulty: 17,
        folgerURL: "AWW",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/allswell/full.html",
        mainImage: require("../assets/images/AWWimage.png"),
        medalImage: require("../assets/medalCollection/mAWW.png")
    },
    {
        id: 1,
        name: "Antony and Cleopatra",
        genre: "Tragedy",
        difficulty: 27,
        folgerURL: "Ant",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/cleopatra/full.html", 
        mainImage: require("../assets/images/ANTimage.png"),
        medalImage: require("../assets/medalCollection/mAnt.png")
    },
    {
        id: 2,
        name: "As You Like It",
        genre: "Comedy",
        difficulty: 5,
        folgerURL: "AYL",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/asyoulikeit/full.html",
        mainImage: require("../assets/images/AYLimage.jpg"),
        medalImage: require("../assets/medalCollection/mAYL.png"),
    },
    {
        id: 3,
        name: "The Comedy of Errors",
        genre: "Comedy",
        difficulty: 6,
        folgerURL: "Err",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/comedy_errors/full.html",
        mainImage: require("../assets/images/Errimage.png"),
        medalImage: require("../assets/medalCollection/mErr.png"),
    },
    {
        id: 4,
        name: "The Winter's Tale",
        genre: "Romance",
        difficulty: 18,
        folgerURL: "WT",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/winters_tale/full.html",
        mainImage: require("../assets/images/WTimage.png"),
        medalImage: require("../assets/medalCollection/mWT.png"),
    },
    {
        id: 5,
        name: "Coriolanus",
        genre: "Tragedy",
        difficulty: 29,
        folgerURL: "Cor",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/coriolanus/full.html",
        mainImage: require("../assets/images/Corimage.png"),
        medalImage: require("../assets/medalCollection/mCor.png"),
    },
    {
        id: 6,
        name: "Cymbeline",
        genre: "Romance",
        difficulty: 19,
        folgerURL: "Cym",
        MITURL: "https://github.com/TheMITTech/shakespeare/blob/master/cymbeline/full.html",
        mainImage: require("../assets/images/Cymimage.png"),
        medalImage: require("../assets/medalCollection/mCym.png"),
    },
    {
        id: 7,
        name: "Hamlet",
        genre: "Tragedy",
        difficulty: 31,
        folgerURL: "Ham",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/1henryiv/index.html",
        mainImage: require("../assets/images/Hamimage.png"),
        medalImage: require("../assets/medalCollection/mHam.png"),
    },
    {
        id: 8,
        name: "Henry IV, Part 1",
        genre: "History",
        difficulty: 12,
        folgerURL: "1H4",
        MITURL: "https://github.com/TheMITTech/shakespeare/blob/master/1henryiv/index.html",
        mainImage: require("../assets/images/1H4image.png"),
        medalImage: require("../assets/medalCollection/m1H4.png"),
    },
    {
        id: 9,
        name: "Henry IV, Part 2",
        genre: "History",
        difficulty: 13,
        folgerURL: "2H4",
        MITURL: "https://github.com/TheMITTech/shakespeare/blob/master/1henryiv/index.html",
        mainImage: require("../assets/images/2H4image.png"),
        medalImage: require("../assets/medalCollection/m2H4.png"),
    },
    {
        id: 10,
        name: "Henry V",
        genre: "History",
        difficulty: 14,
        folgerURL: "H5",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/henryv/full.html",
        mainImage: require("../assets/images/H5image.png"),
        medalImage: require("../assets/medalCollection/mH5.png"),
    },
    {
        id: 11,
        name: "Henry VI, Part 1",
        genre: "History",
        difficulty: 36,
        folgerURL: "1H6",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/1henryvi/full.html",
        mainImage: require("../assets/images/1H6image.png"),
        medalImage: require("../assets/medalCollection/m1H6.png"),
    },
    {
        id: 12,
        name: "Henry VI, Part 2",
        genre: "History",
        difficulty: 37,
        folgerURL: "2H6",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/2henryvi/full.html",
        mainImage: require("../assets/images/2H6image.png"),
        medalImage: require("../assets/medalCollection/m2H6.png"),
    },
    {
        id: 13,
        name: "Henry VI, Part 3",
        genre: "History",
        difficulty: 38,
        folgerURL: "3H6",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/3henryvi/full.html",
        mainImage: require("../assets/images/3H6image.png"),
        medalImage: require("../assets/medalCollection/m3H6.png"),
    },
    {
        id: 14,
        name: "Henry VIII",
        genre: "History",
        folgerURL: "H8",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/henryviii/full.html",
        mainImage: require("../assets/images/H8image.png"),
        medalImage: require("../assets/medalCollection/mH8.png"),
    },
    {
        id: 15,
        name: "Julius Caesar",
        genre: "Tragedy",
        difficulty: 20,
        folgerURL: "JC",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/julius_caesar/full.html",
        mainImage: require("../assets/images/JCimage.png"),
        medalImage: require("../assets/medalCollection/mJC.png"),
    },
    {
        id: 16,
        name: "King John",
        genre: "History",
        difficulty: 21,
        folgerURL: "Jn",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/john/full.html",
        mainImage: require("../assets/images/Jnimage.png"),
        medalImage: require("../assets/medalCollection/mJn.png"),
    },
    {
        id: 17,
        name: "King Lear",
        genre: "Tragedy",
        difficulty: 32,
        folgerURL: "Lr",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/lear/full.html",
        mainImage: require("../assets/images/Lrimage.png"),
        medalImage: require("../assets/medalCollection/mLr.png"),
    },
    {
        id: 18,
        name: "Love's Labor's Lost",
        genre: "Comedy",
        difficulty: 9,
        folgerURL: "LLL",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/lll/full.html",
        mainImage: require("../assets/images/LLLimage.png"),
        medalImage: require("../assets/medalCollection/mLLL.png"),
    },
    {
        id: 19,
        name: "The Scottish Play",
        genre: "Tragedy",
        difficulty: 24,
        folgerURL: "Mac",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/macbeth/full.html",
        mainImage: require("../assets/images/Macimage.png"),
        medalImage: require("../assets/medalCollection/mMac.png"),
    },
    {
        id: 20,
        name: "Measure for Measure",
        genre: "Comedy",
        difficulty: 16,
        folgerURL: "MM",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/measure/full.html",
        mainImage: require("../assets/images/MMimage.png"),
        medalImage: require("../assets/medalCollection/mMM.png"),
    },
    {
        id: 21,
        name: "The Merchant of Venice",
        genre: "Comedy",
        difficulty: 15,
        folgerURL: "MV",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/merchant/full.html",
        mainImage: require("../assets/images/MVimage.png"),
        medalImage: require("../assets/medalCollection/mMV.png"),
    },
    {
        id: 22,
        name: "The Merry Wives of Windsor",
        genre: "Comedy",
        difficulty: 34,
        difficulty: 11,
        folgerURL: "Wiv",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/merry_wives/full.html",
        mainImage: require("../assets/images/Wivimage.png"),
        medalImage: require("../assets/medalCollection/mWiv.png"),
    },
    {
        id: 23,
        name: "A Midsummer Night's Dream",
        genre: "Comedy",
        difficulty: 1,
        folgerURL: "MND",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/midsummer/full.html",
        mainImage: require("../assets/images/MNDimage.jpg"),
        medalImage: require("../assets/medalCollection/mMND.png"),
    },
    {
        id: 24,
        name: "Much Ado About Nothing",
        genre: "Comedy",
        difficulty: 7,
        folgerURL: "Ado",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/much_ado/full.html",
        mainImage: require("../assets/images/Adoimage.png"),
        medalImage: require("../assets/medalCollection/mAdo.png"),
    },
    {
        id: 25,
        name: "Othello",
        genre: "Tragedy",
        difficulty: 25,
        folgerURL: "Oth",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/othello/full.html",
        mainImage: require("../assets/images/Othimage.png"),
        medalImage: require("../assets/medalCollection/mOth.png"),
    },
    {
        id: 26,
        name: "Pericles",
        genre: "Romance",
        difficulty: 26,
        folgerURL: "Per",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/pericles/full.html",
        mainImage: require("../assets/images/Perimage.png"),
        medalImage: require("../assets/medalCollection/mPer.png"),
    },
    {
        id: 27,
        name: "Richard II",
        genre: "History",
        difficulty: 22,
        folgerURL: "R2",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/richardii/full.html",
        mainImage: require("../assets/images/R2image.png"),
        medalImage: require("../assets/medalCollection/mR2.png"),
    },
    {
        id: 28,
        name: "Richard III",
        genre: "History",
        difficulty: 23,
        folgerURL: "R3",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/richardiii/full.html",
        mainImage: require("../assets/images/R3image.png"),
        medalImage: require("../assets/medalCollection/mR3.png"),
    },
    {
        id: 29,
        name: "Romeo and Juliet",
        genre: "Tragedy",
        difficulty: 2,
        folgerURL: "Rom",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/romeo_juliet/full.html",
        mainImage: require("../assets/images/Romimage.jpg"),
        medalImage: require("../assets/medalCollection/mRom.png"),
    },
    {
        id: 30,
        name: "The Taming of the Shrew",
        genre: "Comedy",
        difficulty: 8,
        folgerURL: "Shr",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/taming_shrew/full.html",
        mainImage: require("../assets/images/Shrimage.png"),
        medalImage: require("../assets/medalCollection/mShr.png"),
    },
    {
        id: 31,
        name: "The Tempest",
        genre: "Romance",
        difficulty: 4,
        folgerURL: "Tmp",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/tempest/full.html",
        mainImage: require("../assets/images/Tmpimage.jpg"),
        medalImage: require("../assets/medalCollection/mTmp.png"),
    },
    {
        id: 32,
        name: "Timon of Athens",
        genre: "Tragedy",
        difficulty: 28,
        folgerURL: "Tim",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/timon/full.html",
        mainImage: require("../assets/images/Timimage.png"),
        medalImage: require("../assets/medalCollection/mTim.png"),
    },
    {
        id: 33,
        name: "Titus Andronicus",
        genre: "Tragedy",
        difficulty: 30,
        folgerURL: "Tit",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/titus/full.html",
        mainImage: require("../assets/images/Titimage.png"),
        medalImage: require("../assets/medalCollection/mTit.png"),
    },
    {
        id: 34,
        name: "Troilus and Cressida",
        genre: "Comedy",
        difficulty: 33,
        folgerURL: "Tro",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/troilus_cressida/full.html",
        mainImage: require("../assets/images/Troimage.png"),
        medalImage: require("../assets/medalCollection/mTro.png"),
    },
    {
        id:35,
        name: "Twelfth Night",
        genre: "Comedy",
        difficulty: 3,
        folgerURL: "TN",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/twelfth_night/full.html",
        mainImage: require("../assets/images/TNimage.jpg"),
        medalImage: require("../assets/medalCollection/mTN.png"),
    },
    {
        id: 36,
        name: "Two Gentlemen of Verona",
        genre: "Comedy",
        difficulty: 10,
        folgerURL: "TGV",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/two_gentlemen/full.html",
        mainImage: require("../assets/images/TGVimage.png"),
        medalImage: require("../assets/medalCollection/mTGV.png"),
    },
    {
        id: 37,
        name: "Two Noble Kinsmen",
        genre: "Romance",
        difficulty: 35,
        folgerURL: "TNK",
        MITURL: "https://raw.githubusercontent.com/cobanov/shakespeare-dataset/main/text/the-two-noble-kinsmen_TXT_FolgerShakespeare.txt",
        mainImage: require("../assets/images/TNKimage.png"),
        medalImage: require("../assets/medalCollection/mTNK.png"),
    },
]