export const PLAYS = [
    {
        id: 0,
        name: "All's Well That Ends Well",
        genre: "Comedy",
        difficulty: 17,
        folgerURL: "AWW",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/allswell/full.html",
        mainImage: require("../assets/images/AWWimage.png"),
        medalImage: require("../assets/medalCollection/mAWW.png")
    },
    {
        id: 1,
        name: "Antony and Cleopatra",
        genre: "Tragedy",
        difficulty: 27,
        folgerURL: "Ant",
        MITURL: "https://raw.githubusercontent.com/TheMITTech/shakespeare/master/cleopatra/full.html", 
        mainImage: require("../assets/images/ANTimage.png"),
        medalImage: require("../assets/medalCollection/mANT.png")
    },
    {
        id: 2,
        name: "As You Like It",
        genre: "Comedy",
        difficulty: 5,
        folgerURL: "AYL",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 3,
        name: "The Comedy of Errors",
        genre: "Comedy",
        difficulty: 6,
        folgerURL: "Err",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 4,
        name: "The Winter's Tale",
        genre: "Romance",
        difficulty: 18,
        folgerURL: "WT",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 5,
        name: "Coriolanus",
        genre: "Tragedy",
        difficulty: 29,
        folgerURL: "Cor",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 6,
        name: "Cymbeline",
        genre: "Romance",
        difficulty: 19,
        folgerURL: "Cym",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 7,
        name: "Hamlet",
        genre: "Tragedy",
        difficulty: 31,
        folgerURL: "Ham",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 8,
        name: "Henry IV, Part 1",
        genre: "History",
        difficulty: 12,
        folgerURL: "1H4",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 9,
        name: "Henry IV, Part 2",
        genre: "History",
        difficulty: 13,
        folgerURL: "2H4",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 10,
        name: "Henry V",
        genre: "History",
        difficulty: 14,
        folgerURL: "H5",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 11,
        name: "Henry VI, Part 1",
        genre: "History",
        difficulty: 36,
        difficulty: ,
        folgerURL: "1H6",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 12,
        name: "Henry VI, Part 2",
        genre: "History",
        difficulty: 37,
        folgerURL: "2H6",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 13,
        name: "Henry VI, Part 3",
        genre: "History",
        difficulty: 38,
        folgerURL: "3H6",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 14,
        name: "Henry VIII",
        genre: "History",
        folgerURL: "H8",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 15,
        name: "Julius Caesar",
        genre: "Tragedy",
        difficulty: 20,
        folgerURL: "JC",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 16,
        name: "King John",
        genre: "History",
        difficulty: 21,
        folgerURL: "Jn",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 17,
        name: "King Lear",
        genre: "Tragedy",
        difficulty: 32,
        folgerURL: "Lr",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 18,
        name: "Love's Labor's Lost",
        genre: "Comedy",
        difficulty: 9,
        folgerURL: "LLL",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 19,
        name: "The Scottish Play",
        genre: "Tragedy",
        difficulty: 24,
        folgerURL: "Mac",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 20,
        name: "Measure for Measure",
        genre: "Comedy",
        difficulty: 16,
        folgerURL: "MM",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 21,
        name: "The Merchant of Venice",
        genre: "Comedy",
        difficulty: 15,
        folgerURL: "MV",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 22,
        name: "The Merry Wives of Windsor",
        genre: "Comedy",
        difficulty: 34,
        difficulty: 11,
        folgerURL: "Wiv",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 23,
        name: "A Midsummer Night's Dream",
        genre: "Comedy",
        difficulty: 1,
        folgerURL: "MND",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 24,
        name: "Much Ado About Nothing",
        genre: "Comedy",
        difficulty: 7,
        folgerURL: "Ado",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 25,
        name: "Othello",
        genre: "Tragedy",
        difficulty: 25,
        folgerURL: "Oth",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 26,
        name: "Pericles",
        genre: "Romance",
        difficulty: 26,
        folgerURL: "Per",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 27,
        name: "Richard II",
        genre: "History",
        difficulty: 22,
        folgerURL: "R2",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 28,
        name: "Richard III",
        genre: "History",
        difficulty: 23,
        folgerURL: "R3",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 29,
        name: "Romeo and Juliet",
        genre: "Tragedy",
        difficulty: 2,
        folgerURL: "Rom",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 30,
        name: "The Taming of the Shrew",
        genre: "Comedy",
        difficulty: 8,
        folgerURL: "Shr",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 31,
        name: "The Tempest",
        genre: "Romance",
        difficulty: 4,
        folgerURL: "Tmp",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 32,
        name: "Timon of Athens",
        genre: "Tragedy",
        difficulty: 28,
        folgerURL: "Tim",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 33,
        name: "Titus Andronicus",
        genre: "Tragedy",
        difficulty: 30,
        folgerURL: "Tit",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 34,
        name: "Troilus and Cressida",
        genre: "Comedy",
        difficulty: 33,
        folgerURL: "Tro",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id:35,
        name: "Twelfth Night",
        genre: "Comedy",
        difficulty: 3,
        folgerURL: "TN",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 36,
        name: "Two Gentlemen of Verona",
        genre: "Comedy",
        difficulty: 10,
        folgerURL: "TGV",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
    {
        id: 37,
        name: "Two Noble Kinsmen",
        genre: "Romance",
        difficulty: 35,
        folgerURL: "TNK",
        MITURL:,
        mainImage: require(""),
        medalImage: require(""),
    },
]